# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               CoT AI - a Course Progress
tagline:             'A Jekyll theme'
description:         'A journey to AI'
url:                 ''
baseurl:             '/CoT_AI/'
paginate:            5

# About/contact
author:
  name:              Quang Nguyen
  url:               '/about/'
  email:             ''

# Custom vars
version:             1.0.0

theme: jekyll-theme-merlot

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
